### ISSUE TITLE
Running the Test Suite

### ISSUE THREAD

**Issue by jgarte** [janestreet/timezone#1]
Hi,

OCaml newb here.

How do I run the test suite for `timezone`?

What do you think if we added a target to the Makefile for running the tests?

https://github.com/janestreet/timezone/blob/master/Makefile

**Comment by ceastlund** [comment]
Hi, Jorge.

We currently only run our tests internally, and do not prep them for running externally. Our public release process is automated, and includes automatic generation of things like the Makefile, which we don't actually use internally. So setting up a Makefile that runs our tests successfully would not be as easy as it sounds.

This is something we are working on, as leaving the tests broken in public code is a bad state of things. But it'll take some time.

Sorry I don't have better news for you!
